// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgFw_5OAioa069tVf9B3--yN-J7gPlvW0',
    appId: '1:42089589622:web:40c7990a9595206dbde857',
    messagingSenderId: '42089589622',
    projectId: 'recipe-app-6ad17',
    authDomain: 'recipe-app-6ad17.firebaseapp.com',
    storageBucket: 'recipe-app-6ad17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDONe6lIFRvP3DVeQ3YPJnE4NRwxgMu66I',
    appId: '1:42089589622:android:8c2df01764ab41c4bde857',
    messagingSenderId: '42089589622',
    projectId: 'recipe-app-6ad17',
    storageBucket: 'recipe-app-6ad17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATTjkbnZhhBenoOGP_jYhRSQku8fWG9hU',
    appId: '1:42089589622:ios:a40eff3e5349557fbde857',
    messagingSenderId: '42089589622',
    projectId: 'recipe-app-6ad17',
    storageBucket: 'recipe-app-6ad17.appspot.com',
    iosBundleId: 'com.example.recipeProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATTjkbnZhhBenoOGP_jYhRSQku8fWG9hU',
    appId: '1:42089589622:ios:d1cbfcf08fa01c51bde857',
    messagingSenderId: '42089589622',
    projectId: 'recipe-app-6ad17',
    storageBucket: 'recipe-app-6ad17.appspot.com',
    iosBundleId: 'com.example.recipeProvider.RunnerTests',
  );
}
